name: CI

on:
  push:
    branches: ["main", "develop", "feature-*"]
  pull_request:

jobs:
  ci:
    uses: zaphold2k/ci-workflows/.github/workflows/ci.yml@v1
    with:
      ci_workflows_ref: v1
      language: go
      branch_model: full
      integration_branch: develop
      image_name: ghcr.io/OWNER/REPO
    permissions:
      contents: write
      packages: write
      pull-requests: write
      actions: read
